name: Docker Image CI for GHCR

on:
  push
  
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
      - uses: actions/checkout@v3
      
      - name: build and push the image
        run: |
          docker login --username ${{github.actor}} --password ${{secrets.GITREGPAT}} ghcr.io
          docker build . --tag ghcr.io/${{github.repository}}/echo-app:latest
          docker push ghcr.io/${{github.repository}}/echo-app:latest
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3
        
  #     - name: Set up Docker
  #       uses: docker/setup-buildx-action@v2

  #     - name: Install Minikube
  #       run: |
  #         curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  #         chmod +x minikube
  #         sudo mv minikube /usr/local/bin/

  #     - name: Start Minikube
  #       run: |
  #         minikube start --driver=docker

  #     - name: Set kubectl context for Minikube
  #       run: |
  #         kubectl config use-context minikube

  #     - name: Apply Kubernetes manifest
  #       run: |
  #         kubectl apply -f path/to/your/manifest.yaml

  #     - name: Verify deployment
  #       run: |
  #         kubectl get pods
      
